"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var STATE_ENABLED = 1;
exports.STATE_ENABLED = STATE_ENABLED;
var STATE_DISABLED = 0;
exports.STATE_DISABLED = STATE_DISABLED;
var READ = 'read';
exports.READ = READ;
var CREATE = 'create';
exports.CREATE = CREATE;
var UPDATE = 'update';
exports.UPDATE = UPDATE;
var DELETE = 'delete';
exports.DELETE = DELETE;
